\set ON_ERROR_STOP on
\getenv app_password APP_DB_PASSWORD

BEGIN;

SELECT 'CREATE ROLE career_app'
WHERE NOT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = 'career_app'
)
\gexec

ALTER ROLE career_app
  LOGIN
  PASSWORD :'app_password'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS;

REVOKE ALL ON DATABASE career_agent FROM PUBLIC;
GRANT CONNECT ON DATABASE career_agent TO career_app;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO career_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO career_app;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO career_app;

COMMIT;
