"""create companies and affiliations,

Revision ID: 114b67b6d668
Revises: 
Create Date: 2026-09-14 01:18:00.018418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114b67b6d668'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_key', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.String(length=300), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name='ck_companies_name_not_blank'),
    sa.CheckConstraint('char_length(name_key) = 64', name='ck_companies_name_key_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_key')
    )
    op.create_table('company_affiliations',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('teknopark', sa.String(length=200), nullable=False),
    sa.Column('source_target_sector', sa.Boolean(), nullable=True),
    sa.CheckConstraint('char_length(btrim(teknopark)) > 0', name='ck_affiliations_teknopark_not_blank'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'teknopark')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_affiliations')
    op.drop_table('companies')
    # ### end Alembic commands ###
