"""add career sources

Revision ID: 1301e7dd3cd0
Revises: b85b63dbe6d6
Create Date: 2026-09-17 22:27:10.125187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1301e7dd3cd0'
down_revision: Union[str, Sequence[str], None] = 'b85b63dbe6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('ats_type', sa.String(length=30), nullable=True),
    sa.Column('access_strategy', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='candidate', nullable=False),
    sa.Column('discovered_from_url', sa.String(length=2048), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access_strategy IN ('public_api', 'allowed_crawl', 'browser_assisted', 'manual_import', 'blocked')", name='ck_career_sources_access_strategy'),
    sa.CheckConstraint("ats_type IS NULL OR ats_type IN ('lever', 'greenhouse', 'smartrecruiters', 'recruitee', 'workable', 'ashby', 'teamtailor', 'custom')", name='ck_career_sources_ats_type'),
    sa.CheckConstraint("source_type <> 'ats' OR ats_type IS NOT NULL", name='ck_career_sources_ats_requires_type'),
    sa.CheckConstraint("source_type IN ('ats', 'career_page', 'jobs_page', 'manual')", name='ck_career_sources_type'),
    sa.CheckConstraint("status IN ('candidate', 'active', 'inactive', 'blocked', 'needs_review')", name='ck_career_sources_status'),
    sa.CheckConstraint('char_length(btrim(source_url)) > 0', name='ck_career_sources_url_not_blank'),
    sa.CheckConstraint('consecutive_failures BETWEEN 0 AND 1000', name='ck_career_sources_failure_count'),
    sa.CheckConstraint('last_http_status IS NULL OR last_http_status BETWEEN 100 AND 599', name='ck_career_sources_http_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_url', name='uq_career_sources_company_url')
    )
    op.create_index('ix_career_sources_status_next_check', 'career_sources', ['status', 'next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_career_sources_status_next_check', table_name='career_sources')
    op.drop_table('career_sources')
    # ### end Alembic commands ###
