"""add company discovery tables

Revision ID: 924c669eac75
Revises: 114b67b6d668
Create Date: 2026-09-14 22:26:49.792837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '924c669eac75'
down_revision: Union[str, Sequence[str], None] = '114b67b6d668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_web_profiles',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=300), nullable=True),
    sa.Column('official_website_url', sa.String(length=2048), nullable=True),
    sa.Column('careers_url', sa.String(length=2048), nullable=True),
    sa.Column('official_linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='low', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='needs_review', nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('search_provider', sa.String(length=50), server_default='serper', nullable=False),
    sa.Column('evaluator_model', sa.String(length=100), server_default='gemini-3.6-flash', nullable=False),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('high', 'medium', 'low')", name='ck_company_web_profiles_confidence'),
    sa.CheckConstraint("status <> 'not_found' OR (official_website_url IS NULL AND careers_url IS NULL AND official_linkedin_url IS NULL)", name='ck_company_web_profiles_not_found_has_no_urls'),
    sa.CheckConstraint("status <> 'verified' OR (last_verified_at IS NOT NULL AND official_website_url IS NOT NULL)", name='ck_company_web_profiles_verified_fields'),
    sa.CheckConstraint("status IN ('candidate_found', 'verified', 'needs_review', 'not_found')", name='ck_company_web_profiles_status'),
    sa.CheckConstraint("status NOT IN ('candidate_found', 'verified') OR official_website_url IS NOT NULL", name='ck_company_web_profiles_candidate_has_website'),
    sa.CheckConstraint('careers_url IS NULL OR char_length(btrim(careers_url)) > 0', name='ck_company_web_profiles_careers_not_blank'),
    sa.CheckConstraint('official_linkedin_url IS NULL OR char_length(btrim(official_linkedin_url)) > 0', name='ck_company_web_profiles_linkedin_not_blank'),
    sa.CheckConstraint('official_website_url IS NULL OR char_length(btrim(official_website_url)) > 0', name='ck_company_web_profiles_website_not_blank'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('discovery_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('search_provider', sa.String(length=50), server_default='serper', nullable=False),
    sa.Column('evaluator_model', sa.String(length=100), nullable=True),
    sa.Column('result_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('success', 'no_results', 'search_error', 'evaluation_error', 'rejected')", name='ck_discovery_attempts_outcome'),
    sa.CheckConstraint('char_length(btrim(query)) > 0', name='ck_discovery_attempts_query_not_blank'),
    sa.CheckConstraint('result_count BETWEEN 0 AND 100', name='ck_discovery_attempts_result_count'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discovery_attempts_company_created', 'discovery_attempts', ['company_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discovery_attempts_company_created', table_name='discovery_attempts')
    op.drop_table('discovery_attempts')
    op.drop_table('company_web_profiles')
    # ### end Alembic commands ###
