"""enforce not found confidence

Revision ID: b85b63dbe6d6
Revises: 924c669eac75
Create Date: 2026-09-15 03:26:28.319114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85b63dbe6d6'
down_revision: Union[str, Sequence[str], None] = '924c669eac75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            UPDATE company_web_profiles
            SET
                confidence = 'low',
                brand_name = NULL,
                evidence = '[]'::jsonb,
                updated_at = now()
            WHERE
                status = 'not_found'
                AND (
                    confidence <> 'low'
                    OR brand_name IS NOT NULL
                    OR evidence <> '[]'::jsonb
                )
            """
        )
    )

    op.create_check_constraint(
        "ck_company_web_profiles_not_found_confidence",
        "company_web_profiles",
        "status <> 'not_found' OR confidence = 'low'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_company_web_profiles_not_found_confidence",
        "company_web_profiles",
        type_="check",
    )
    # ### end Alembic commands ###
